import os
import colorama
import time
from colorama import Fore, Back, Style
from colorama import init

init()

    
print(Fore. CYAN)    
print("Hello, Lera")    
print(Fore. MAGENTA)
print("▄───▄")   
print("█▀█▀█")   
print("█▄█▄█")   
print("─███──▄▄")   
print("─████▐█─█")   
print("─████───█")   
print("─▀▀▀▀▀▀▀")   
print(Fore. GREEN)
os.system("apt update && apt upgrade")
time.sleep(3)
os.sytem(y)
os.system("apt install bash -y && apt indtall pip -y && apt install git")
os.sytem(y)
time.sleep(3)
os.sytem(y)
os.system("apt install python -y && apt install python2")
time.sleep(3)
os.sytem(y)
os.system("apt install pcap")
os.sytem(y)
time.sleep(4)
os.system("apt install openssh")
os.sytem(y)
time.sleep(4)
os.system("apt install scapy")
os.sytem(y)
time.sleep(4)
os.system("apt install wget")
os.sytem(y)
time.sleep(4)
os.system("apt install curl")
os.sytem(y)
time.sleep(4)
os.system("apt install php")
os.sytem(y)
time.sleep(4)
print(Fore. GREEN)
print("Усе, закончили.")